name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull mellusb/cicd-pipeline-portfolio:latest
    - name: Delete Old docker container
      run: sudo docker rm -f mellusb-pipeline-container-portfolio || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3001:3001 --name cicd-pipeline-portfolio-container mellusb/cicd-pipeline-portfolio